In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#import geopandas as gpd

%matplotlib inline

### IMPORT ALL THE DATA

In [ ]:
#Zipcode geodata (Only needed if buiding a map... i think.. will need to be in geospatial)
#zip = gpd.read_file('../data/zipcodes.geojson')
#zip

In [2]:
#COVID CASES
cases = pd.read_csv('../data/COVID_CountByZipPerDate 03292021.csv')

#VACCINATIONS
vacc = pd.read_csv('../data/vaccine_with_protocol.csv')

#INCOME
income = pd.read_csv('../data/household_income_2019.csv')

#AGE and SEX
age = pd.read_csv('../data/sex_age_2019.csv')

#SEX and EDU
edu = pd.read_csv('../data/sex_edu_attainment_over 25_2019.csv')

#RACE
race = pd.read_csv('../data/race_ethnicity_2019.csv')

In [ ]:
cases
#cases.isnull().sum()

In [ ]:
vacc
#vacc.isnull().sum()

In [ ]:
income.tail()
#income.isnull().sum()

In [ ]:
age
age_sum = age.groupby(['name']).sum()
age_sum

In [ ]:
edu.tail()

In [ ]:
race

### DATA INFO

In [ ]:
cases.info()

In [ ]:
vacc.info()

In [ ]:
income.info()

In [ ]:
age.info()

In [ ]:
edu.info()

In [ ]:
race.info()

### CLEAN THE DATA (remove unwanted columns- rename rows - make it easy to change out columns)

In [16]:
#COVID CASES - df cases
#remove N/A zipcode data
cases = cases.dropna()
#convert to int 
cases = cases.astype({"Zip": int})
#convert to date
cases['Specimen Collection Date'] = pd.to_datetime(cases['Specimen Collection Date'], format='%m/%d/%Y')

sum_cases = cases.groupby(['Zip']).sum()
sum_cases.drop()
sum_cases

       Cases
Zip
37013  13354
37027    231
37069     16
37072   2984
37076   4279
37080    574
37115   4574
37138   2359
37189    479
37201    299
37203   3346
37204   1786
37205   2566
37206   3112
37207   4729
37208   2428
37209   5072
37210   2100
37211  10233
37212   1823
37213     65
37214   3508
37215   2438
37216   2011
37217   3907
37218   1785
37219    270
37220    656
37221   3910
37228    310
37238      3

In [19]:
#VACCINATIONS- df vacc
#remove N/A zipcode data
vacc = vacc.dropna()
#convert to int 
vacc = vacc.astype({"zipcode": int})
vacc = vacc.astype({"count_given": int})
vacc = vacc.astype({"dose_nbr": int})
#convert to date
vacc['vacc_date'] = pd.to_datetime(vacc['vacc_date'], format='%Y-%m-%d')
#replace shots/brand and convert to int
vacc['protocol'] = vacc['protocol'].replace('one-shot', 1)
vacc['protocol'] = vacc['protocol'].replace('two-shot', 2)
vacc = vacc.astype({"protocol": int})
#add column for completed vs incomplete vaccinations
vacc['incomplete vaccinations'] = vacc.protocol - vacc.dose_nbr

In [ ]:
#INCOME - df income
income.drop(['geoid','B19001001, Error','B19001002, Error','B19001003, Error','B19001004, Error','B19001005, Error','B19001006, Error','B19001007, Error','B19001008, Error','B19001009, Error','B19001010, Error','B19001011, Error','B19001012, Error','B19001013, Error','B19001014, Error','B19001014, Error','B19001015, Error','B19001016, Error','B19001017, Error'], inplace=True, axis=1)

In [ ]:
#AGE and SEX - df age

In [ ]:
#SEX and EDU - df sex

In [ ]:
#RACE- df race

### MERGE THE DATA on zipcode

In [18]:
casesvage = sum_cases.merge(age,how='left', left_on='Zip', right_on='name')
casesvage

,Cases,geoid,name,B01001001,"B01001001, Error",B01001002,"B01001002, Error",B01001003,"B01001003, Error",B01001004,...,B01001045,"B01001045, Error",B01001046,"B01001046, Error",B01001047,"B01001047, Error",B01001048,"B01001048, Error",B01001049,"B01001049, Error"
0,13354,86000US37013,37013.0,97939.0,2456.0,47658.0,1617.0,4550.0,514.0,3786.0,...,757.0,193.0,1019.0,240.0,571.0,208.0,315.0,130.0,233.0,82.0
1,231,86000US37027,37027.0,56117.0,765.0,27888.0,915.0,1561.0,245.0,2093.0,...,892.0,145.0,1145.0,159.0,748.0,134.0,538.0,142.0,280.0,82.0
2,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2984,86000US37072,37072.0,31492.0,763.0,15327.0,585.0,881.0,203.0,1131.0,...,668.0,137.0,814.0,197.0,596.0,145.0,333.0,107.0,478.0,120.0
4,4279,86000US37076,37076.0,40161.0,1183.0,19600.0,774.0,1457.0,309.0,1273.0,...,484.0,111.0,850.0,160.0,477.0,139.0,524.0,141.0,296.0,96.0
5,574,86000US37080,37080.0,7394.0,587.0,3703.0,327.0,175.0,83.0,110.0,...,192.0,65.0,135.0,58.0,115.0,58.0,64.0,38.0,81.0,45.0
6,4574,86000US37115,37115.0,40343.0,1599.0,19376.0,1057.0,1486.0,355.0,1509.0,...,691.0,190.0,741.0,191.0,405.0,116.0,484.0,129.0,444.0,103.0
7,2359,86000US37138,37138.0,23784.0,1002.0,11320.0,642.0,609.0,170.0,476.0,...,602.0,171.0,438.0,157.0,316.0,131.0,231.0,119.0,193.0,110.0
8,479,86000US37189,37189.0,4016.0,458.0,1642.0,250.0,104.0,61.0,46.0,...,47.0,41.0,134.0,57.0,27.0,27.0,47.0,27.0,54.0,61.0
9,299,86000US37201,37201.0,1619.0,387.0,1245.0,310.0,0.0,12.0,0.0,...,0.0,12.0,0.0,12.0,0.0,12.0,0.0,12.0,0.0,12.0
10,3346,86000US37203,37203.0,15091.0,896.0,7412.0,638.0,245.0,133.0,206.0,...,79.0,58.0,122.0,58.0,110.0,84.0,49.0,43.0,39.0,41.0
11,1786,86000US37204,37204.0,15452.0,766.0,6908.0,442.0,634.0,191.0,272.0,...,164.0,68.0,188.0,72.0,144.0,56.0,54.0,42.0,75.0,34.0
12,2566,86000US37205,37205.0,23790.0,885.0,10824.0,622.0,484.0,147.0,528.0,...,578.0,133.0,650.0,148.0,452.0,120.0,437.0,128.0,741.0,158.0
13,3112,86000US37206,37206.0,26382.0,1266.0,12473.0,736.0,844.0,243.0,835.0,...,172.0,85.0,357.0,113.0,228.0,95.0,164.0,93.0,112.0,53.0
14,4729,86000US37207,37207.0,39544.0,1499.0,17866.0,971.0,1600.0,310.0,1433.0,...,601.0,182.0,636.0,198.0,531.0,158.0,343.0,99.0,429.0,155.0
15,2428,86000US37208,37208.0,18011.0,1111.0,7917.0,722.0,456.0,176.0,242.0,...,248.0,103.0,186.0,80.0,99.0,87.0,133.0,65.0,150.0,65.0
16,5072,86000US37209,37209.0,38664.0,1540.0,18251.0,962.0,1037.0,282.0,1122.0,...,400.0,113.0,423.0,187.0,419.0,133.0,233.0,82.0,223.0,81.0
17,2100,86000US37210,37210.0,17248.0,934.0,8731.0,661.0,934.0,226.0,497.0,...,183.0,73.0,231.0,86.0,202.0,78.0,158.0,66.0,196.0,92.0
18,10233,86000US37211,37211.0,75955.0,1962.0,39340.0,1438.0,2821.0,372.0,2268.0,...,982.0,201.0,894.0,178.0,663.0,166.0,555.0,213.0,623.0,145.0
19,1823,86000US37212,37212.0,20803.0,1042.0,9757.0,706.0,375.0,128.0,226.0,...,103.0,54.0,188.0,76.0,101.0,63.0,80.0,55.0,232.0,93.0
20,65,86000US37213,37213.0,95.0,120.0,86.0,121.0,0.0,12.0,0.0,...,0.0,12.0,0.0,12.0,0.0,12.0,0.0,12.0,0.0,12.0
21,3508,86000US37214,37214.0,30528.0,1060.0,14968.0,792.0,683.0,181.0,901.0,...,413.0,107.0,507.0,185.0,552.0,166.0,298.0,110.0,420.0,124.0
22,2438,86000US37215,37215.0,22379.0,959.0,9989.0,504.0,607.0,158.0,534.0,...,351.0,101.0,698.0,156.0,520.0,136.0,351.0,105.0,584.0,159.0
23,2011,86000US37216,37216.0,17848.0,909.0,8877.0,637.0,435.0,96.0,421.0,...,276.0,100.0,243.0,85.0,183.0,79.0,198.0,98.0,205.0,83.0
24,3907,86000US37217,37217.0,30146.0,1416.0,15018.0,952.0,1348.0,286.0,1035.0,...,551.0,175.0,265.0,85.0,291.0,119.0,149.0,72.0,53.0,36.0
25,1785,86000US37218,37218.0,15721.0,928.0,7083.0,631.0,324.0,166.0,462.0,...,366.0,154.0,385.0,112.0,352.0,119.0,178.0,98.0,183.0,94.0
26,270,86000US37219,37219.0,1154.0,380.0,737.0,310.0,0.0,12.0,0.0,...,39.0,61.0,0.0,12.0,0.0,12.0,0.0,12.0,0.0,12.0
27,656,86000US37220,37220.0,5880.0,413.0,2994.0,293.0,315.0,101.0,283.0,...,80.0,47.0,78.0,45.0,141.0,79.0,79.0,45.0,128.0,78.0
28,3910,86000US37221,37221.0,41017.0,1119.0,19437.0,767.0,1508.0,289.0,1354.0,...,704.0,152.0,903.0,138.0,815.0,160.0,494.0,133.0,362.0,109.0
29,310,86000US37228,37228.0,1615.0,363.0,708.0,284.0,0.0,12.0,0.0,...,121.0,122.0,31.0,30.0,17.0,29.0,21.0,29.0,15.0,14.0
30,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
nan_value = float("NaN")
casesvage = casesvage.replace(" ",nan_value,inplace=True)
casesvage = casesvage.dropna()

AttributeError: 'NoneType' object has no attribute 'dropna'

In [6]:
casesvage = casesvage.apply(pd.to_numeric, errors='coerce')
casesvage = casesvage.dropna()

In [ ]:
casesvage = casesvage.astype({"name": int})
casesvage = casesvage.astype({"Cases": int})
casesvage = casesvage.astype({"B01001003": int})

In [ ]:

casesvage_zip = casesvage[(casesvage.Zip)] 
casesvage_cases = casesvage[(casesvage.Cases)]         
casesvage_age = casesvage[(casesvage.B01001003)] 

                                                      
                                                      
plt.scatter(casesvage_drill)

### EXPLORATORY ANALYSIS - try the pairplot

### BUBBLE CHART with correlating data