In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#import geopandas as gpd

%matplotlib inline

### IMPORT ALL THE DATA

In [ ]:
#Zipcode geodata (Only needed if buiding a map... i think.. will need to be in geospatial)
#zip = gpd.read_file('../data/zipcodes.geojson')
#zip

In [2]:
#COVID CASES
cases = pd.read_csv('../data/COVID_CountByZipPerDate 03292021.csv')

#VACCINATIONS
vacc = pd.read_csv('../data/vaccine_with_protocol.csv')

#INCOME
income = pd.read_csv('../data/household_income_2019.csv')

#AGE and SEX
age = pd.read_excel('../data/acs2019_5yr_B01001_86000US37243/acs2019_5yr_B01001_86000US37243.xlsx', skiprows = 1, header=[0, 1], sheet_name = 0)

#SEX and EDU
edu = pd.read_csv('../data/sex_edu_attainment_over 25_2019.csv')

#RACE
race = pd.read_csv('../data/race_ethnicity_2019.csv')

In [ ]:
cases
#cases.isnull().sum()

In [ ]:
vacc
#vacc.isnull().sum()

In [ ]:
#age = age.transpose()
#age.rename{index={0:}}
age.info()

### CLEAN THE DATA (remove unwanted columns- rename rows - make it easy to change out columns)

In [4]:
#COVID CASES - df cases
#remove N/A zipcode data
cases = cases.dropna()
#convert to int 
cases = cases.astype({"Zip": int})
#convert to date
cases['Specimen Collection Date'] = pd.to_datetime(cases['Specimen Collection Date'], format='%m/%d/%Y')

sum_cases = cases.groupby(['Zip']).sum()
sum_cases = sum_cases[sum_cases['Cases']>16]

In [5]:
#VACCINATIONS- df vacc
#remove N/A zipcode data
vacc = vacc.dropna()
#convert to int 
vacc = vacc.astype({"zipcode": int})
vacc = vacc.astype({"count_given": int})
vacc = vacc.astype({"dose_nbr": int})
#convert to date
vacc['vacc_date'] = pd.to_datetime(vacc['vacc_date'], format='%Y-%m-%d')
#replace shots/brand and convert to int
vacc['protocol'] = vacc['protocol'].replace('one-shot', 1)
vacc['protocol'] = vacc['protocol'].replace('two-shot', 2)
vacc = vacc.astype({"protocol": int})
#add column for completed vs incomplete vaccinations
vacc['incomplete vaccinations'] = vacc.protocol - vacc.dose_nbr

In [6]:
#AGE and SEX - df age
#drop columns from merged cells issue
age = age[age.columns.drop(list(age.filter(regex='Error')))]
age.columns = age.columns.droplevel(1)
#set column names 
age = age.set_index('Unnamed: 0_level_0').T.reset_index().rename({"index": "zipcode"}, axis = 1)
#convert
age = age.astype({"zipcode": int})

### MERGE THE DATA on zipcode

In [15]:
casesvage = sum_cases.merge(age,how='left', left_on='Zip', right_on='zipcode')
casesvage

,Cases,zipcode,Total:,Male:,Under 5 years,5 to 9 years,10 to 14 years,15 to 17 years,18 and 19 years,20 years,...,50 to 54 years,55 to 59 years,60 and 61 years,62 to 64 years,65 and 66 years,67 to 69 years,70 to 74 years,75 to 79 years,80 to 84 years,85 years and over
0,13354,37013,97939,47658,4550,3786,3656,1727,1107,210,...,2899,2785,1236,1286,871,757,1019,571,315,233
1,231,37027,56117,27888,1561,2093,2511,1771,673,179,...,2043,2311,770,1086,786,892,1145,748,538,280
2,2984,37072,31492,15327,881,1131,950,529,301,195,...,1419,1283,594,379,403,668,814,596,333,478
3,4279,37076,40161,19600,1457,1273,1063,543,307,131,...,1200,1380,704,551,400,484,850,477,524,296
4,574,37080,7394,3703,175,110,163,85,63,17,...,324,490,73,162,56,192,135,115,64,81
5,4574,37115,40343,19376,1486,1509,1311,577,368,227,...,1264,1362,553,657,497,691,741,405,484,444
6,2359,37138,23784,11320,609,476,900,513,323,192,...,964,905,434,403,299,602,438,316,231,193
7,479,37189,4016,1642,104,46,142,54,16,0,...,159,177,83,79,87,47,134,27,47,54
8,299,37201,1619,1245,0,0,30,0,94,14,...,22,38,0,86,34,0,0,0,0,0
9,3346,37203,15091,7412,245,206,60,110,149,82,...,278,334,65,147,127,79,122,110,49,39
10,1786,37204,15452,6908,634,272,256,127,434,172,...,423,361,177,193,126,164,188,144,54,75
11,2566,37205,23790,10824,484,528,475,245,176,155,...,768,1018,409,497,363,578,650,452,437,741
12,3112,37206,26382,12473,844,835,664,365,387,200,...,701,751,223,383,172,172,357,228,164,112
13,4729,37207,39544,17866,1600,1433,1368,762,517,80,...,1587,1481,442,598,344,601,636,531,343,429
14,2428,37208,18011,7917,456,242,797,350,247,207,...,515,481,242,328,249,248,186,99,133,150
15,5072,37209,38664,18251,1037,1122,1040,456,494,206,...,868,1000,246,585,236,400,423,419,233,223
16,2100,37210,17248,8731,934,497,615,200,364,162,...,337,579,250,177,110,183,231,202,158,196
17,10233,37211,75955,39340,2821,2268,1998,1424,594,632,...,1684,2522,711,751,642,982,894,663,555,623
18,1823,37212,20803,9757,375,226,323,332,1424,579,...,354,446,220,157,179,103,188,101,80,232
19,65,37213,95,86,0,0,0,10,0,0,...,0,0,0,0,0,0,0,0,0,0
20,3508,37214,30528,14968,683,901,929,431,294,58,...,1206,1242,234,545,257,413,507,552,298,420
21,2438,37215,22379,9989,607,534,460,253,179,33,...,779,848,460,427,323,351,698,520,351,584
22,2011,37216,17848,8877,435,421,240,190,242,17,...,475,725,183,431,202,276,243,183,198,205
23,3907,37217,30146,15018,1348,1035,704,487,432,102,...,860,862,445,420,269,551,265,291,149,53
24,1785,37218,15721,7083,324,462,441,391,166,26,...,605,454,333,291,305,366,385,352,178,183
25,270,37219,1154,737,0,0,0,0,0,0,...,170,0,0,70,0,39,0,0,0,0
26,656,37220,5880,2994,315,283,177,77,20,0,...,255,231,138,148,47,80,78,141,79,128
27,3910,37221,41017,19437,1508,1354,1002,730,294,111,...,1557,1871,468,921,591,704,903,815,494,362
28,310,37228,1615,708,0,0,0,0,28,16,...,95,47,17,0,46,121,31,17,21,15

In [14]:
#combine sex

In [16]:
#separate age groups
age.ages_u15 =
age.ages_u30 =
age.ages_u60 =
age.ages_o60 =

SyntaxError: invalid syntax (<ipython-input-16-fed0e7eeab01>, line 2)

### EXPLORATORY ANALYSIS - try the pairplot

### BUBBLE CHART with correlating data